# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mon blog
email: alexis@via.ecp.fr
description: > # this means to ignore newlines until "baseurl:"
  Blog perso Alexis de Lattre
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexis-via.github.io" # the base hostname & protocol for your site
twitter_username: alexisdlattre
github_username:  alexis-via

# Build settings
markdown: kramdown
